// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: object_gateway.proto

package objectgatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectStatusCode int32

const (
	ObjectStatusCode_OBJECT_STATUS_OK                    ObjectStatusCode = 0
	ObjectStatusCode_OBJECT_STATUS_NOT_FOUND             ObjectStatusCode = 1
	ObjectStatusCode_OBJECT_STATUS_SIZE_LIMIT            ObjectStatusCode = 2
	ObjectStatusCode_OBJECT_STATUS_STORAGE_TIMEOUT       ObjectStatusCode = 3
	ObjectStatusCode_OBJECT_STATUS_STORAGE_RETRIABLE     ObjectStatusCode = 4
	ObjectStatusCode_OBJECT_STATUS_STORAGE_NON_RETRIABLE ObjectStatusCode = 5
	ObjectStatusCode_OBJECT_STATUS_DEADLINE_EXCEEDED     ObjectStatusCode = 6
	ObjectStatusCode_OBJECT_STATUS_CANCELLED             ObjectStatusCode = 7
	ObjectStatusCode_OBJECT_STATUS_INTERNAL              ObjectStatusCode = 8
)

// Enum value maps for ObjectStatusCode.
var (
	ObjectStatusCode_name = map[int32]string{
		0: "OBJECT_STATUS_OK",
		1: "OBJECT_STATUS_NOT_FOUND",
		2: "OBJECT_STATUS_SIZE_LIMIT",
		3: "OBJECT_STATUS_STORAGE_TIMEOUT",
		4: "OBJECT_STATUS_STORAGE_RETRIABLE",
		5: "OBJECT_STATUS_STORAGE_NON_RETRIABLE",
		6: "OBJECT_STATUS_DEADLINE_EXCEEDED",
		7: "OBJECT_STATUS_CANCELLED",
		8: "OBJECT_STATUS_INTERNAL",
	}
	ObjectStatusCode_value = map[string]int32{
		"OBJECT_STATUS_OK":                    0,
		"OBJECT_STATUS_NOT_FOUND":             1,
		"OBJECT_STATUS_SIZE_LIMIT":            2,
		"OBJECT_STATUS_STORAGE_TIMEOUT":       3,
		"OBJECT_STATUS_STORAGE_RETRIABLE":     4,
		"OBJECT_STATUS_STORAGE_NON_RETRIABLE": 5,
		"OBJECT_STATUS_DEADLINE_EXCEEDED":     6,
		"OBJECT_STATUS_CANCELLED":             7,
		"OBJECT_STATUS_INTERNAL":              8,
	}
)

func (x ObjectStatusCode) Enum() *ObjectStatusCode {
	p := new(ObjectStatusCode)
	*p = x
	return p
}

func (x ObjectStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_object_gateway_proto_enumTypes[0].Descriptor()
}

func (ObjectStatusCode) Type() protoreflect.EnumType {
	return &file_object_gateway_proto_enumTypes[0]
}

func (x ObjectStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectStatusCode.Descriptor instead.
func (ObjectStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{0}
}

type StorageStatusClass int32

const (
	StorageStatusClass_STORAGE_STATUS_NONE          StorageStatusClass = 0
	StorageStatusClass_STORAGE_STATUS_TIMEOUT       StorageStatusClass = 1
	StorageStatusClass_STORAGE_STATUS_RETRIABLE     StorageStatusClass = 2
	StorageStatusClass_STORAGE_STATUS_NON_RETRIABLE StorageStatusClass = 3
)

// Enum value maps for StorageStatusClass.
var (
	StorageStatusClass_name = map[int32]string{
		0: "STORAGE_STATUS_NONE",
		1: "STORAGE_STATUS_TIMEOUT",
		2: "STORAGE_STATUS_RETRIABLE",
		3: "STORAGE_STATUS_NON_RETRIABLE",
	}
	StorageStatusClass_value = map[string]int32{
		"STORAGE_STATUS_NONE":          0,
		"STORAGE_STATUS_TIMEOUT":       1,
		"STORAGE_STATUS_RETRIABLE":     2,
		"STORAGE_STATUS_NON_RETRIABLE": 3,
	}
)

func (x StorageStatusClass) Enum() *StorageStatusClass {
	p := new(StorageStatusClass)
	*p = x
	return p
}

func (x StorageStatusClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageStatusClass) Descriptor() protoreflect.EnumDescriptor {
	return file_object_gateway_proto_enumTypes[1].Descriptor()
}

func (StorageStatusClass) Type() protoreflect.EnumType {
	return &file_object_gateway_proto_enumTypes[1]
}

func (x StorageStatusClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageStatusClass.Descriptor instead.
func (StorageStatusClass) EnumDescriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{1}
}

type ObjectIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectIdentity) Reset() {
	*x = ObjectIdentity{}
	mi := &file_object_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectIdentity) ProtoMessage() {}

func (x *ObjectIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectIdentity.ProtoReflect.Descriptor instead.
func (*ObjectIdentity) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectIdentity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ObjectIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ObjectMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *ObjectIdentity        `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Generation    uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Etag          string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	UserMetadata  map[string]string      `protobuf:"bytes,6,rep,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMetadata) Reset() {
	*x = ObjectMetadata{}
	mi := &file_object_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMetadata) ProtoMessage() {}

func (x *ObjectMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMetadata.ProtoReflect.Descriptor instead.
func (*ObjectMetadata) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectMetadata) GetObject() *ObjectIdentity {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *ObjectMetadata) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ObjectMetadata) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ObjectMetadata) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ObjectMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ObjectMetadata) GetUserMetadata() map[string]string {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

type OperationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ObjectStatusCode       `protobuf:"varint,1,opt,name=code,proto3,enum=kimojio.examples.object_gateway.v1.ObjectStatusCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StorageClass  StorageStatusClass     `protobuf:"varint,3,opt,name=storage_class,json=storageClass,proto3,enum=kimojio.examples.object_gateway.v1.StorageStatusClass" json:"storage_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStatus) Reset() {
	*x = OperationStatus{}
	mi := &file_object_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStatus) ProtoMessage() {}

func (x *OperationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStatus.ProtoReflect.Descriptor instead.
func (*OperationStatus) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *OperationStatus) GetCode() ObjectStatusCode {
	if x != nil {
		return x.Code
	}
	return ObjectStatusCode_OBJECT_STATUS_OK
}

func (x *OperationStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationStatus) GetStorageClass() StorageStatusClass {
	if x != nil {
		return x.StorageClass
	}
	return StorageStatusClass_STORAGE_STATUS_NONE
}

type PutChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *ObjectIdentity        `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Finish        bool                   `protobuf:"varint,4,opt,name=finish,proto3" json:"finish,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	UserMetadata  map[string]string      `protobuf:"bytes,6,rep,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunk) Reset() {
	*x = PutChunk{}
	mi := &file_object_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunk) ProtoMessage() {}

func (x *PutChunk) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunk.ProtoReflect.Descriptor instead.
func (*PutChunk) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *PutChunk) GetObject() *ObjectIdentity {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *PutChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PutChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutChunk) GetFinish() bool {
	if x != nil {
		return x.Finish
	}
	return false
}

func (x *PutChunk) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PutChunk) GetUserMetadata() map[string]string {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *OperationStatus       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      *ObjectMetadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_object_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *PutResponse) GetStatus() *OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PutResponse) GetMetadata() *ObjectMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *ObjectIdentity        `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	MaxChunkBytes uint32                 `protobuf:"varint,2,opt,name=max_chunk_bytes,json=maxChunkBytes,proto3" json:"max_chunk_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_object_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetObject() *ObjectIdentity {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *GetRequest) GetMaxChunkBytes() uint32 {
	if x != nil {
		return x.MaxChunkBytes
	}
	return 0
}

type GetChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *OperationStatus       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      *ObjectMetadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Finish        bool                   `protobuf:"varint,5,opt,name=finish,proto3" json:"finish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunk) Reset() {
	*x = GetChunk{}
	mi := &file_object_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunk) ProtoMessage() {}

func (x *GetChunk) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunk.ProtoReflect.Descriptor instead.
func (*GetChunk) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetChunk) GetStatus() *OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetChunk) GetMetadata() *ObjectMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetChunk) GetFinish() bool {
	if x != nil {
		return x.Finish
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *ObjectIdentity        `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_object_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetObject() *ObjectIdentity {
	if x != nil {
		return x.Object
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *OperationStatus       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_object_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetStatus() *OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	MaxResults    uint32                 `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_object_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListRequest) GetMaxResults() uint32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *OperationStatus       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Objects       []*ObjectMetadata      `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_object_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetStatus() *OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListResponse) GetObjects() []*ObjectMetadata {
	if x != nil {
		return x.Objects
	}
	return nil
}

type CopyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *ObjectIdentity        `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   *ObjectIdentity        `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyRequest) Reset() {
	*x = CopyRequest{}
	mi := &file_object_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRequest) ProtoMessage() {}

func (x *CopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyRequest.ProtoReflect.Descriptor instead.
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *CopyRequest) GetSource() *ObjectIdentity {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *CopyRequest) GetDestination() *ObjectIdentity {
	if x != nil {
		return x.Destination
	}
	return nil
}

type CopyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *OperationStatus       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      *ObjectMetadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyResponse) Reset() {
	*x = CopyResponse{}
	mi := &file_object_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResponse) ProtoMessage() {}

func (x *CopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResponse.ProtoReflect.Descriptor instead.
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *CopyResponse) GetStatus() *OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CopyResponse) GetMetadata() *ObjectMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_object_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{13}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	ShuttingDown  bool                   `protobuf:"varint,2,opt,name=shutting_down,json=shuttingDown,proto3" json:"shutting_down,omitempty"`
	InFlight      uint64                 `protobuf:"varint,3,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	Completed     uint64                 `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	Failed        uint64                 `protobuf:"varint,5,opt,name=failed,proto3" json:"failed,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_object_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_object_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_object_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetShuttingDown() bool {
	if x != nil {
		return x.ShuttingDown
	}
	return false
}

func (x *HealthResponse) GetInFlight() uint64 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *HealthResponse) GetCompleted() uint64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *HealthResponse) GetFailed() uint64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_object_gateway_proto protoreflect.FileDescriptor

const file_object_gateway_proto_rawDesc = "" +
	"\n" +
	"\x14object_gateway.proto\x12\"kimojio.examples.object_gateway.v1\"B\n" +
	"\x0eObjectIdentity\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xfe\x02\n" +
	"\x0eObjectMetadata\x12J\n" +
	"\x06object\x18\x01 \x01(\v22.kimojio.examples.object_gateway.v1.ObjectIdentityR\x06object\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12i\n" +
	"\ruser_metadata\x18\x06 \x03(\v2D.kimojio.examples.object_gateway.v1.ObjectMetadata.UserMetadataEntryR\fuserMetadata\x1a?\n" +
	"\x11UserMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd2\x01\n" +
	"\x0fOperationStatus\x12H\n" +
	"\x04code\x18\x01 \x01(\x0e24.kimojio.examples.object_gateway.v1.ObjectStatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12[\n" +
	"\rstorage_class\x18\x03 \x01(\x0e26.kimojio.examples.object_gateway.v1.StorageStatusClassR\fstorageClass\"\xe3\x02\n" +
	"\bPutChunk\x12J\n" +
	"\x06object\x18\x01 \x01(\v22.kimojio.examples.object_gateway.v1.ObjectIdentityR\x06object\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x16\n" +
	"\x06finish\x18\x04 \x01(\bR\x06finish\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12c\n" +
	"\ruser_metadata\x18\x06 \x03(\v2>.kimojio.examples.object_gateway.v1.PutChunk.UserMetadataEntryR\fuserMetadata\x1a?\n" +
	"\x11UserMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x01\n" +
	"\vPutResponse\x12K\n" +
	"\x06status\x18\x01 \x01(\v23.kimojio.examples.object_gateway.v1.OperationStatusR\x06status\x12N\n" +
	"\bmetadata\x18\x02 \x01(\v22.kimojio.examples.object_gateway.v1.ObjectMetadataR\bmetadata\"\x80\x01\n" +
	"\n" +
	"GetRequest\x12J\n" +
	"\x06object\x18\x01 \x01(\v22.kimojio.examples.object_gateway.v1.ObjectIdentityR\x06object\x12&\n" +
	"\x0fmax_chunk_bytes\x18\x02 \x01(\rR\rmaxChunkBytes\"\xeb\x01\n" +
	"\bGetChunk\x12K\n" +
	"\x06status\x18\x01 \x01(\v23.kimojio.examples.object_gateway.v1.OperationStatusR\x06status\x12N\n" +
	"\bmetadata\x18\x02 \x01(\v22.kimojio.examples.object_gateway.v1.ObjectMetadataR\bmetadata\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x16\n" +
	"\x06finish\x18\x05 \x01(\bR\x06finish\"[\n" +
	"\rDeleteRequest\x12J\n" +
	"\x06object\x18\x01 \x01(\v22.kimojio.examples.object_gateway.v1.ObjectIdentityR\x06object\"]\n" +
	"\x0eDeleteResponse\x12K\n" +
	"\x06status\x18\x01 \x01(\v23.kimojio.examples.object_gateway.v1.OperationStatusR\x06status\"d\n" +
	"\vListRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\rR\n" +
	"maxResults\"\xa9\x01\n" +
	"\fListResponse\x12K\n" +
	"\x06status\x18\x01 \x01(\v23.kimojio.examples.object_gateway.v1.OperationStatusR\x06status\x12L\n" +
	"\aobjects\x18\x02 \x03(\v22.kimojio.examples.object_gateway.v1.ObjectMetadataR\aobjects\"\xaf\x01\n" +
	"\vCopyRequest\x12J\n" +
	"\x06source\x18\x01 \x01(\v22.kimojio.examples.object_gateway.v1.ObjectIdentityR\x06source\x12T\n" +
	"\vdestination\x18\x02 \x01(\v22.kimojio.examples.object_gateway.v1.ObjectIdentityR\vdestination\"\xab\x01\n" +
	"\fCopyResponse\x12K\n" +
	"\x06status\x18\x01 \x01(\v23.kimojio.examples.object_gateway.v1.OperationStatusR\x06status\x12N\n" +
	"\bmetadata\x18\x02 \x01(\v22.kimojio.examples.object_gateway.v1.ObjectMetadataR\bmetadata\"\x0f\n" +
	"\rHealthRequest\"\xb8\x01\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12#\n" +
	"\rshutting_down\x18\x02 \x01(\bR\fshuttingDown\x12\x1b\n" +
	"\tin_flight\x18\x03 \x01(\x04R\binFlight\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\x04R\tcompleted\x12\x16\n" +
	"\x06failed\x18\x05 \x01(\x04R\x06failed\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion*\xb2\x02\n" +
	"\x10ObjectStatusCode\x12\x14\n" +
	"\x10OBJECT_STATUS_OK\x10\x00\x12\x1b\n" +
	"\x17OBJECT_STATUS_NOT_FOUND\x10\x01\x12\x1c\n" +
	"\x18OBJECT_STATUS_SIZE_LIMIT\x10\x02\x12!\n" +
	"\x1dOBJECT_STATUS_STORAGE_TIMEOUT\x10\x03\x12#\n" +
	"\x1fOBJECT_STATUS_STORAGE_RETRIABLE\x10\x04\x12'\n" +
	"#OBJECT_STATUS_STORAGE_NON_RETRIABLE\x10\x05\x12#\n" +
	"\x1fOBJECT_STATUS_DEADLINE_EXCEEDED\x10\x06\x12\x1b\n" +
	"\x17OBJECT_STATUS_CANCELLED\x10\a\x12\x1a\n" +
	"\x16OBJECT_STATUS_INTERNAL\x10\b*\x89\x01\n" +
	"\x12StorageStatusClass\x12\x17\n" +
	"\x13STORAGE_STATUS_NONE\x10\x00\x12\x1a\n" +
	"\x16STORAGE_STATUS_TIMEOUT\x10\x01\x12\x1c\n" +
	"\x18STORAGE_STATUS_RETRIABLE\x10\x02\x12 \n" +
	"\x1cSTORAGE_STATUS_NON_RETRIABLE\x10\x032\x96\x05\n" +
	"\rObjectGateway\x12f\n" +
	"\x03Put\x12,.kimojio.examples.object_gateway.v1.PutChunk\x1a/.kimojio.examples.object_gateway.v1.PutResponse(\x01\x12e\n" +
	"\x03Get\x12..kimojio.examples.object_gateway.v1.GetRequest\x1a,.kimojio.examples.object_gateway.v1.GetChunk0\x01\x12o\n" +
	"\x06Delete\x121.kimojio.examples.object_gateway.v1.DeleteRequest\x1a2.kimojio.examples.object_gateway.v1.DeleteResponse\x12i\n" +
	"\x04List\x12/.kimojio.examples.object_gateway.v1.ListRequest\x1a0.kimojio.examples.object_gateway.v1.ListResponse\x12i\n" +
	"\x04Copy\x12/.kimojio.examples.object_gateway.v1.CopyRequest\x1a0.kimojio.examples.object_gateway.v1.CopyResponse\x12o\n" +
	"\x06Health\x121.kimojio.examples.object_gateway.v1.HealthRequest\x1a2.kimojio.examples.object_gateway.v1.HealthResponseBNZLgithub.com/Azure/kimojio-rs/examples/go/object_gateway/proto;objectgatewayv1b\x06proto3"

var (
	file_object_gateway_proto_rawDescOnce sync.Once
	file_object_gateway_proto_rawDescData []byte
)

func file_object_gateway_proto_rawDescGZIP() []byte {
	file_object_gateway_proto_rawDescOnce.Do(func() {
		file_object_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_object_gateway_proto_rawDesc), len(file_object_gateway_proto_rawDesc)))
	})
	return file_object_gateway_proto_rawDescData
}

var file_object_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_object_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_object_gateway_proto_goTypes = []any{
	(ObjectStatusCode)(0),   // 0: kimojio.examples.object_gateway.v1.ObjectStatusCode
	(StorageStatusClass)(0), // 1: kimojio.examples.object_gateway.v1.StorageStatusClass
	(*ObjectIdentity)(nil),  // 2: kimojio.examples.object_gateway.v1.ObjectIdentity
	(*ObjectMetadata)(nil),  // 3: kimojio.examples.object_gateway.v1.ObjectMetadata
	(*OperationStatus)(nil), // 4: kimojio.examples.object_gateway.v1.OperationStatus
	(*PutChunk)(nil),        // 5: kimojio.examples.object_gateway.v1.PutChunk
	(*PutResponse)(nil),     // 6: kimojio.examples.object_gateway.v1.PutResponse
	(*GetRequest)(nil),      // 7: kimojio.examples.object_gateway.v1.GetRequest
	(*GetChunk)(nil),        // 8: kimojio.examples.object_gateway.v1.GetChunk
	(*DeleteRequest)(nil),   // 9: kimojio.examples.object_gateway.v1.DeleteRequest
	(*DeleteResponse)(nil),  // 10: kimojio.examples.object_gateway.v1.DeleteResponse
	(*ListRequest)(nil),     // 11: kimojio.examples.object_gateway.v1.ListRequest
	(*ListResponse)(nil),    // 12: kimojio.examples.object_gateway.v1.ListResponse
	(*CopyRequest)(nil),     // 13: kimojio.examples.object_gateway.v1.CopyRequest
	(*CopyResponse)(nil),    // 14: kimojio.examples.object_gateway.v1.CopyResponse
	(*HealthRequest)(nil),   // 15: kimojio.examples.object_gateway.v1.HealthRequest
	(*HealthResponse)(nil),  // 16: kimojio.examples.object_gateway.v1.HealthResponse
	nil,                     // 17: kimojio.examples.object_gateway.v1.ObjectMetadata.UserMetadataEntry
	nil,                     // 18: kimojio.examples.object_gateway.v1.PutChunk.UserMetadataEntry
}
var file_object_gateway_proto_depIdxs = []int32{
	2,  // 0: kimojio.examples.object_gateway.v1.ObjectMetadata.object:type_name -> kimojio.examples.object_gateway.v1.ObjectIdentity
	17, // 1: kimojio.examples.object_gateway.v1.ObjectMetadata.user_metadata:type_name -> kimojio.examples.object_gateway.v1.ObjectMetadata.UserMetadataEntry
	0,  // 2: kimojio.examples.object_gateway.v1.OperationStatus.code:type_name -> kimojio.examples.object_gateway.v1.ObjectStatusCode
	1,  // 3: kimojio.examples.object_gateway.v1.OperationStatus.storage_class:type_name -> kimojio.examples.object_gateway.v1.StorageStatusClass
	2,  // 4: kimojio.examples.object_gateway.v1.PutChunk.object:type_name -> kimojio.examples.object_gateway.v1.ObjectIdentity
	18, // 5: kimojio.examples.object_gateway.v1.PutChunk.user_metadata:type_name -> kimojio.examples.object_gateway.v1.PutChunk.UserMetadataEntry
	4,  // 6: kimojio.examples.object_gateway.v1.PutResponse.status:type_name -> kimojio.examples.object_gateway.v1.OperationStatus
	3,  // 7: kimojio.examples.object_gateway.v1.PutResponse.metadata:type_name -> kimojio.examples.object_gateway.v1.ObjectMetadata
	2,  // 8: kimojio.examples.object_gateway.v1.GetRequest.object:type_name -> kimojio.examples.object_gateway.v1.ObjectIdentity
	4,  // 9: kimojio.examples.object_gateway.v1.GetChunk.status:type_name -> kimojio.examples.object_gateway.v1.OperationStatus
	3,  // 10: kimojio.examples.object_gateway.v1.GetChunk.metadata:type_name -> kimojio.examples.object_gateway.v1.ObjectMetadata
	2,  // 11: kimojio.examples.object_gateway.v1.DeleteRequest.object:type_name -> kimojio.examples.object_gateway.v1.ObjectIdentity
	4,  // 12: kimojio.examples.object_gateway.v1.DeleteResponse.status:type_name -> kimojio.examples.object_gateway.v1.OperationStatus
	4,  // 13: kimojio.examples.object_gateway.v1.ListResponse.status:type_name -> kimojio.examples.object_gateway.v1.OperationStatus
	3,  // 14: kimojio.examples.object_gateway.v1.ListResponse.objects:type_name -> kimojio.examples.object_gateway.v1.ObjectMetadata
	2,  // 15: kimojio.examples.object_gateway.v1.CopyRequest.source:type_name -> kimojio.examples.object_gateway.v1.ObjectIdentity
	2,  // 16: kimojio.examples.object_gateway.v1.CopyRequest.destination:type_name -> kimojio.examples.object_gateway.v1.ObjectIdentity
	4,  // 17: kimojio.examples.object_gateway.v1.CopyResponse.status:type_name -> kimojio.examples.object_gateway.v1.OperationStatus
	3,  // 18: kimojio.examples.object_gateway.v1.CopyResponse.metadata:type_name -> kimojio.examples.object_gateway.v1.ObjectMetadata
	5,  // 19: kimojio.examples.object_gateway.v1.ObjectGateway.Put:input_type -> kimojio.examples.object_gateway.v1.PutChunk
	7,  // 20: kimojio.examples.object_gateway.v1.ObjectGateway.Get:input_type -> kimojio.examples.object_gateway.v1.GetRequest
	9,  // 21: kimojio.examples.object_gateway.v1.ObjectGateway.Delete:input_type -> kimojio.examples.object_gateway.v1.DeleteRequest
	11, // 22: kimojio.examples.object_gateway.v1.ObjectGateway.List:input_type -> kimojio.examples.object_gateway.v1.ListRequest
	13, // 23: kimojio.examples.object_gateway.v1.ObjectGateway.Copy:input_type -> kimojio.examples.object_gateway.v1.CopyRequest
	15, // 24: kimojio.examples.object_gateway.v1.ObjectGateway.Health:input_type -> kimojio.examples.object_gateway.v1.HealthRequest
	6,  // 25: kimojio.examples.object_gateway.v1.ObjectGateway.Put:output_type -> kimojio.examples.object_gateway.v1.PutResponse
	8,  // 26: kimojio.examples.object_gateway.v1.ObjectGateway.Get:output_type -> kimojio.examples.object_gateway.v1.GetChunk
	10, // 27: kimojio.examples.object_gateway.v1.ObjectGateway.Delete:output_type -> kimojio.examples.object_gateway.v1.DeleteResponse
	12, // 28: kimojio.examples.object_gateway.v1.ObjectGateway.List:output_type -> kimojio.examples.object_gateway.v1.ListResponse
	14, // 29: kimojio.examples.object_gateway.v1.ObjectGateway.Copy:output_type -> kimojio.examples.object_gateway.v1.CopyResponse
	16, // 30: kimojio.examples.object_gateway.v1.ObjectGateway.Health:output_type -> kimojio.examples.object_gateway.v1.HealthResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_object_gateway_proto_init() }
func file_object_gateway_proto_init() {
	if File_object_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_object_gateway_proto_rawDesc), len(file_object_gateway_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_object_gateway_proto_goTypes,
		DependencyIndexes: file_object_gateway_proto_depIdxs,
		EnumInfos:         file_object_gateway_proto_enumTypes,
		MessageInfos:      file_object_gateway_proto_msgTypes,
	}.Build()
	File_object_gateway_proto = out.File
	file_object_gateway_proto_goTypes = nil
	file_object_gateway_proto_depIdxs = nil
}
