// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: object_gateway.proto

package objectgatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObjectGateway_Put_FullMethodName    = "/kimojio.examples.object_gateway.v1.ObjectGateway/Put"
	ObjectGateway_Get_FullMethodName    = "/kimojio.examples.object_gateway.v1.ObjectGateway/Get"
	ObjectGateway_Delete_FullMethodName = "/kimojio.examples.object_gateway.v1.ObjectGateway/Delete"
	ObjectGateway_List_FullMethodName   = "/kimojio.examples.object_gateway.v1.ObjectGateway/List"
	ObjectGateway_Copy_FullMethodName   = "/kimojio.examples.object_gateway.v1.ObjectGateway/Copy"
	ObjectGateway_Health_FullMethodName = "/kimojio.examples.object_gateway.v1.ObjectGateway/Health"
)

// ObjectGatewayClient is the client API for ObjectGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObjectGatewayClient interface {
	Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutChunk, PutResponse], error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChunk], error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type objectGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectGatewayClient(cc grpc.ClientConnInterface) ObjectGatewayClient {
	return &objectGatewayClient{cc}
}

func (c *objectGatewayClient) Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutChunk, PutResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObjectGateway_ServiceDesc.Streams[0], ObjectGateway_Put_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutChunk, PutResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObjectGateway_PutClient = grpc.ClientStreamingClient[PutChunk, PutResponse]

func (c *objectGatewayClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObjectGateway_ServiceDesc.Streams[1], ObjectGateway_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, GetChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObjectGateway_GetClient = grpc.ServerStreamingClient[GetChunk]

func (c *objectGatewayClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ObjectGateway_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectGatewayClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, ObjectGateway_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectGatewayClient) Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyResponse)
	err := c.cc.Invoke(ctx, ObjectGateway_Copy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectGatewayClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ObjectGateway_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectGatewayServer is the server API for ObjectGateway service.
// All implementations must embed UnimplementedObjectGatewayServer
// for forward compatibility.
type ObjectGatewayServer interface {
	Put(grpc.ClientStreamingServer[PutChunk, PutResponse]) error
	Get(*GetRequest, grpc.ServerStreamingServer[GetChunk]) error
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Copy(context.Context, *CopyRequest) (*CopyResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedObjectGatewayServer()
}

// UnimplementedObjectGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObjectGatewayServer struct{}

func (UnimplementedObjectGatewayServer) Put(grpc.ClientStreamingServer[PutChunk, PutResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedObjectGatewayServer) Get(*GetRequest, grpc.ServerStreamingServer[GetChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedObjectGatewayServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedObjectGatewayServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedObjectGatewayServer) Copy(context.Context, *CopyRequest) (*CopyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Copy not implemented")
}
func (UnimplementedObjectGatewayServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedObjectGatewayServer) mustEmbedUnimplementedObjectGatewayServer() {}
func (UnimplementedObjectGatewayServer) testEmbeddedByValue()                       {}

// UnsafeObjectGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjectGatewayServer will
// result in compilation errors.
type UnsafeObjectGatewayServer interface {
	mustEmbedUnimplementedObjectGatewayServer()
}

func RegisterObjectGatewayServer(s grpc.ServiceRegistrar, srv ObjectGatewayServer) {
	// If the following call pancis, it indicates UnimplementedObjectGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObjectGateway_ServiceDesc, srv)
}

func _ObjectGateway_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ObjectGatewayServer).Put(&grpc.GenericServerStream[PutChunk, PutResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObjectGateway_PutServer = grpc.ClientStreamingServer[PutChunk, PutResponse]

func _ObjectGateway_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObjectGatewayServer).Get(m, &grpc.GenericServerStream[GetRequest, GetChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObjectGateway_GetServer = grpc.ServerStreamingServer[GetChunk]

func _ObjectGateway_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectGatewayServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectGateway_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectGatewayServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectGateway_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectGatewayServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectGateway_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectGatewayServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectGateway_Copy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectGatewayServer).Copy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectGateway_Copy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectGatewayServer).Copy(ctx, req.(*CopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectGateway_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectGatewayServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectGateway_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectGatewayServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObjectGateway_ServiceDesc is the grpc.ServiceDesc for ObjectGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjectGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kimojio.examples.object_gateway.v1.ObjectGateway",
	HandlerType: (*ObjectGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _ObjectGateway_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ObjectGateway_List_Handler,
		},
		{
			MethodName: "Copy",
			Handler:    _ObjectGateway_Copy_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ObjectGateway_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _ObjectGateway_Put_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _ObjectGateway_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "object_gateway.proto",
}
