[package]
name = "websocket-chat"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
virtual-clock = ["kimojio/virtual-clock"]

[dependencies]
futures.workspace = true
kimojio.workspace = true
kimojio-fsm-http1.workspace = true
kimojio-fsm-websocket.workspace = true
rustix.workspace = true
